/**
 * USEL → JavaScript Compiler
 *
 * Converts a USEL AST into runnable JavaScript code.
 *
 * Translation strategy:
 *   Subject–Predicate–Object  →  predicate(subject, object)
 *   Modifiers                 →  property bags or wrapper calls
 *   Conditionals (IF …)       →  if (condition) { body }
 *   Compute primes            →  direct function calls (add, loop, …)
 *   Nested predicates         →  right-to-left nesting
 *
 * Examples:
 *   [I, WANT, SEE, SOMETHING, BIG]  → want(self, see(something({ size: "big" })))
 *   [IF, SOMETHING, BAD, HAPPEN, DO, MOVE] → if (isBad(something())) { doAction(move()); }
 *   [COMPUTE_ADD, 2, 3]              → add(2, 3)
 */

import type { USELAST, USELNode, USELStatement } from '../primes/types.js';
import {
  analyseStatement,
  classifyNode,
  toCamelCase,
  isConditional,
  splitConditional,
  type AnalysedStatement,
} from './utils.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Compile an entire USEL AST to JavaScript source. */
export function compileToJS(ast: USELAST): string {
  if (!ast.statements.length) return '// empty USEL program\n';

  const lines: string[] = [
    '// Generated by USEL → JavaScript compiler',
    `// USEL v${ast.metadata.version}  |  level ${ast.metadata.level}`,
    '',
  ];

  for (const stmt of ast.statements) {
    lines.push(compileStatement(stmt) + ';');
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Statement compilation
// ---------------------------------------------------------------------------

function compileStatement(stmt: USELStatement): string {
  if (stmt.nodes.length === 0) return '/* empty statement */';

  // ---- Conditional path ----
  if (isConditional(stmt)) {
    return compileConditional(stmt);
  }

  // ---- Explicit condition sub-statement ----
  if (stmt.condition) {
    const cond = compileStatement(stmt.condition);
    const body = compileStatementBody(stmt);
    return `if (${cond}) {\n  ${body};\n}`;
  }

  return compileStatementBody(stmt);
}

// ---------------------------------------------------------------------------
// Conditional compilation
// ---------------------------------------------------------------------------

function compileConditional(stmt: USELStatement): string {
  const { conditionNodes, bodyNodes } = splitConditional(stmt);

  const condExpr = conditionNodes.length
    ? compileNodeSequence(conditionNodes)
    : 'true';

  const bodyExpr = bodyNodes.length
    ? compileNodeSequence(bodyNodes)
    : '/* no action */';

  return `if (${condExpr}) {\n  ${bodyExpr};\n}`;
}

// ---------------------------------------------------------------------------
// Core expression builder
// ---------------------------------------------------------------------------

/**
 * Compile the non-conditional body of a statement by analysing roles and
 * building a nested function-call expression.
 */
function compileStatementBody(stmt: USELStatement): string {
  const analysis = analyseStatement(stmt);

  // Pure compute statement (e.g. COMPUTE_ADD 2 3)
  if (analysis.computes.length > 0 && !analysis.subject && analysis.predicates.length === 0) {
    return compileComputeExpression(analysis);
  }

  return buildExpression(analysis);
}

/**
 * Turn an analysed statement into a JS expression string.
 *
 * Builds from right-to-left: the innermost object gets wrapped by each
 * predicate outward, with the subject as the first argument of the
 * outermost predicate.
 */
function buildExpression(a: AnalysedStatement): string {
  // Start with the object(s)
  let inner = a.objects.length
    ? a.objects.map(o => compileObjectNode(o, a)).join(', ')
    : '';

  // Wrap predicates right-to-left (innermost predicate wraps object first)
  const preds = [...a.predicates].reverse();
  for (const pred of preds) {
    const fnName = toCamelCase(pred.symbol.name);
    inner = inner ? `${fnName}(${inner})` : `${fnName}()`;
  }

  // Prepend subject
  if (a.subject) {
    const subjectStr = compileSubjectNode(a.subject);
    if (inner) {
      // Inject subject as first arg of outermost call
      const parenIdx = inner.indexOf('(');
      if (parenIdx !== -1) {
        const fnPart = inner.slice(0, parenIdx + 1);
        const argsPart = inner.slice(parenIdx + 1);
        inner = argsPart.startsWith(')')
          ? `${fnPart}${subjectStr})`
          : `${fnPart}${subjectStr}, ${argsPart}`;
      } else {
        inner = `${inner}(${subjectStr})`;
      }
    } else {
      inner = subjectStr;
    }
  }

  // Append temporal / spatial adverbs as comments (informational)
  const adverbs: string[] = [];
  for (const t of a.temporals) adverbs.push(toCamelCase(t.symbol.name));
  for (const s of a.spatials)  adverbs.push(toCamelCase(s.symbol.name));
  if (adverbs.length) {
    inner += ` /* ${adverbs.join(', ')} */`;
  }

  return inner || '/* no expression */';
}

// ---------------------------------------------------------------------------
// Node-level helpers
// ---------------------------------------------------------------------------

/** Render a subject node (e.g. I → self, YOU → target). */
function compileSubjectNode(node: USELNode): string {
  const name = node.symbol.name.toUpperCase();
  switch (name) {
    case 'I':       return 'self';
    case 'YOU':     return 'target';
    case 'SOMEONE': return 'someone()';
    case 'PEOPLE':  return 'people()';
    default:        return toCamelCase(node.symbol.name);
  }
}

/** Render an object node, including any modifiers attached to it. */
function compileObjectNode(node: USELNode, a: AnalysedStatement): string {
  const name = node.symbol.name.toUpperCase();
  const mods = a.modifierMap.get(node.id) ?? [];

  let base: string;
  switch (name) {
    case 'SOMETHING': base = 'something'; break;
    case 'THIS':      base = 'this_';     break;
    default:          base = toCamelCase(node.symbol.name); break;
  }

  if (mods.length === 0) {
    return node.children.length
      ? `${base}(${node.children.map(c => compileChildNode(c)).join(', ')})`
      : `${base}()`;
  }

  // Build a property bag from modifiers
  const props = mods.map(m => modifierToProp(m)).join(', ');
  return `${base}({ ${props} })`;
}

/**
 * Convert a modifier node to a JS property string.
 * Evaluators become boolean checkers; descriptors become size/quality props.
 */
function modifierToProp(mod: USELNode): string {
  const name = mod.symbol.name.toUpperCase();
  const cat = mod.symbol.category;

  if (cat === 'evaluator') {
    switch (name) {
      case 'GOOD': return 'quality: "good"';
      case 'BAD':  return 'quality: "bad"';
      default:     return `${toCamelCase(mod.symbol.name)}: true`;
    }
  }

  if (cat === 'descriptor') {
    switch (name) {
      case 'BIG':   return 'size: "big"';
      case 'SMALL': return 'size: "small"';
      case 'LONG':  return 'length: "long"';
      case 'SHORT': return 'length: "short"';
      default:      return `${toCamelCase(mod.symbol.name)}: true`;
    }
  }

  if (cat === 'intensifier') {
    switch (name) {
      case 'VERY': return 'intensity: "very"';
      case 'MORE': return 'intensity: "more"';
      case 'NOT':  return 'negated: true';
      default:     return `${toCamelCase(mod.symbol.name)}: true`;
    }
  }

  return `${toCamelCase(mod.symbol.name)}: true`;
}

/** Recursively compile a child node of any type. */
function compileChildNode(node: USELNode): string {
  const role = classifyNode(node);

  if (role === 'compute') {
    return compileComputeNode(node);
  }

  const fnName = toCamelCase(node.symbol.name);
  if (node.children.length === 0) return `${fnName}()`;
  const args = node.children.map(c => compileChildNode(c)).join(', ');
  return `${fnName}(${args})`;
}

// ---------------------------------------------------------------------------
// Compute expression compilation
// ---------------------------------------------------------------------------

/**
 * Compile a compute-category expression.
 * Handles math ops, control flow (LOOP), comparisons, IO, etc.
 */
function compileComputeExpression(a: AnalysedStatement): string {
  return a.computes.map(c => compileComputeNode(c)).join(';\n');
}

function compileComputeNode(node: USELNode): string {
  const name = node.symbol.name.toUpperCase();
  const cat = node.symbol.category;

  const args = node.children.map(c => {
    // Literal numeric children — check if name is a number
    const num = Number(c.symbol.name);
    if (!isNaN(num)) return String(num);
    return compileChildNode(c);
  });

  // Math operations
  if (cat === 'math') {
    const fnName = name.replace(/^COMPUTE_/, '').toLowerCase();
    return `${fnName}(${args.join(', ')})`;
  }

  // Control flow
  if (cat === 'control') {
    if (name === 'LOOP' || name === 'COMPUTE_LOOP') {
      const count = args[0] ?? 'n';
      const body  = args[1] ?? '/* body */';
      return `for (let i = 0; i < ${count}; i++) {\n  ${body};\n}`;
    }
    return `${toCamelCase(name)}(${args.join(', ')})`;
  }

  // Comparison
  if (cat === 'compare') {
    const op = name.replace(/^COMPUTE_/, '').toLowerCase();
    if (args.length >= 2) {
      const opMap: Record<string, string> = {
        equal: '===', notequal: '!==',
        greater: '>', less: '<',
        greaterequal: '>=', lessequal: '<=',
      };
      return `(${args[0]} ${opMap[op] ?? '==='} ${args[1]})`;
    }
    return `${op}(${args.join(', ')})`;
  }

  // IO
  if (cat === 'io') {
    const fnName = name.replace(/^COMPUTE_/, '').toLowerCase();
    return `${fnName}(${args.join(', ')})`;
  }

  // Generic fallback
  const fnName = toCamelCase(name);
  return `${fnName}(${args.join(', ')})`;
}

// ---------------------------------------------------------------------------
// Sequence compiler (used for inline conditional fragments)
// ---------------------------------------------------------------------------

/**
 * Compile a raw list of nodes (e.g. the condition or body half of
 * an inline IF statement) into a JS expression.
 */
function compileNodeSequence(nodes: USELNode[]): string {
  // Quick path: check for evaluator-wrapped pattern like [SOMETHING, BAD, HAPPEN]
  const modifiers  = nodes.filter(n => classifyNode(n) === 'modifier');
  const subjects   = nodes.filter(n => classifyNode(n) === 'subject');
  const predicates = nodes.filter(n => classifyNode(n) === 'predicate');

  // Build something like isBad(something())
  if (modifiers.length > 0 && (subjects.length > 0 || predicates.length > 0)) {
    const evalMod = modifiers.find(m => m.symbol.category === 'evaluator');
    const subj = subjects[0];
    if (evalMod && subj) {
      const checker = `is${evalMod.symbol.name.charAt(0).toUpperCase()}${evalMod.symbol.name.slice(1).toLowerCase()}`;
      const subjStr = compileSubjectNode(subj);
      // If there's a predicate too (e.g. HAPPEN), wrap further
      if (predicates.length > 0) {
        const pred = toCamelCase(predicates[0].symbol.name);
        return `${checker}(${pred}(${subjStr}))`;
      }
      return `${checker}(${subjStr})`;
    }
  }

  // Generic: nest predicates around objects
  const fakeStmt: USELStatement = { type: 'statement', nodes };
  const analysis = analyseStatement(fakeStmt);
  return buildExpression(analysis);
}
