/**
 * USEL → Python Compiler
 *
 * Converts a USEL AST into idiomatic Python source code.
 *
 * Follows the same structural analysis as the JS compiler but emits
 * snake_case identifiers, Python dict literals, and Python control flow.
 *
 * Examples:
 *   [I, WANT, SEE, SOMETHING, BIG]  → want(self, see(something(size='big')))
 *   [IF, SOMETHING, BAD, HAPPEN, DO, MOVE] → if is_bad(something()):\n    do_action(move())
 *   [COMPUTE_ADD, 2, 3]              → add(2, 3)
 */

import type { USELAST, USELNode, USELStatement } from '../primes/types.js';
import {
  analyseStatement,
  classifyNode,
  toSnakeCase,
  isConditional,
  splitConditional,
  type AnalysedStatement,
} from './utils.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/** Compile an entire USEL AST to Python source. */
export function compileToPython(ast: USELAST): string {
  if (!ast.statements.length) return '# empty USEL program\n';

  const lines: string[] = [
    '# Generated by USEL → Python compiler',
    `# USEL v${ast.metadata.version}  |  level ${ast.metadata.level}`,
    '',
  ];

  for (const stmt of ast.statements) {
    lines.push(compileStatement(stmt));
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Statement compilation
// ---------------------------------------------------------------------------

function compileStatement(stmt: USELStatement, indent = 0): string {
  const pad = '    '.repeat(indent);
  if (stmt.nodes.length === 0) return `${pad}pass  # empty statement`;

  if (isConditional(stmt)) {
    return compileConditional(stmt, indent);
  }

  if (stmt.condition) {
    const cond = compileStatement(stmt.condition);
    const body = compileStatementBody(stmt);
    return `${pad}if ${cond}:\n${pad}    ${body}`;
  }

  return `${pad}${compileStatementBody(stmt)}`;
}

// ---------------------------------------------------------------------------
// Conditional compilation
// ---------------------------------------------------------------------------

function compileConditional(stmt: USELStatement, indent = 0): string {
  const pad = '    '.repeat(indent);
  const { conditionNodes, bodyNodes } = splitConditional(stmt);

  const condExpr = conditionNodes.length
    ? compileNodeSequence(conditionNodes)
    : 'True';

  const bodyExpr = bodyNodes.length
    ? compileNodeSequence(bodyNodes)
    : 'pass';

  return `${pad}if ${condExpr}:\n${pad}    ${bodyExpr}`;
}

// ---------------------------------------------------------------------------
// Core expression builder
// ---------------------------------------------------------------------------

function compileStatementBody(stmt: USELStatement): string {
  const analysis = analyseStatement(stmt);

  if (analysis.computes.length > 0 && !analysis.subject && analysis.predicates.length === 0) {
    return compileComputeExpression(analysis);
  }

  return buildExpression(analysis);
}

/**
 * Build a Python expression from an analysed statement.
 * Same nesting strategy as the JS compiler but with Python conventions.
 */
function buildExpression(a: AnalysedStatement): string {
  let inner = a.objects.length
    ? a.objects.map(o => compileObjectNode(o, a)).join(', ')
    : '';

  // Nest predicates right-to-left
  const preds = [...a.predicates].reverse();
  for (const pred of preds) {
    const fnName = toSnakeCase(pred.symbol.name);
    inner = inner ? `${fnName}(${inner})` : `${fnName}()`;
  }

  // Prepend subject
  if (a.subject) {
    const subj = compileSubjectNode(a.subject);
    if (inner) {
      const parenIdx = inner.indexOf('(');
      if (parenIdx !== -1) {
        const fnPart = inner.slice(0, parenIdx + 1);
        const argsPart = inner.slice(parenIdx + 1);
        inner = argsPart.startsWith(')')
          ? `${fnPart}${subj})`
          : `${fnPart}${subj}, ${argsPart}`;
      } else {
        inner = `${inner}(${subj})`;
      }
    } else {
      inner = subj;
    }
  }

  // Temporal/spatial adverbs as comments
  const adverbs: string[] = [];
  for (const t of a.temporals) adverbs.push(toSnakeCase(t.symbol.name));
  for (const s of a.spatials)  adverbs.push(toSnakeCase(s.symbol.name));
  if (adverbs.length) {
    inner += `  # ${adverbs.join(', ')}`;
  }

  return inner || 'pass  # no expression';
}

// ---------------------------------------------------------------------------
// Node-level helpers
// ---------------------------------------------------------------------------

function compileSubjectNode(node: USELNode): string {
  const name = node.symbol.name.toUpperCase();
  switch (name) {
    case 'I':       return 'self';
    case 'YOU':     return 'target';
    case 'SOMEONE': return 'someone()';
    case 'PEOPLE':  return 'people()';
    default:        return toSnakeCase(node.symbol.name);
  }
}

function compileObjectNode(node: USELNode, a: AnalysedStatement): string {
  const name = node.symbol.name.toUpperCase();
  const mods = a.modifierMap.get(node.id) ?? [];

  let base: string;
  switch (name) {
    case 'SOMETHING': base = 'something'; break;
    case 'THIS':      base = 'this_ref';  break;
    default:          base = toSnakeCase(node.symbol.name); break;
  }

  if (mods.length === 0) {
    return node.children.length
      ? `${base}(${node.children.map(c => compileChildNode(c)).join(', ')})`
      : `${base}()`;
  }

  // Python keyword args for modifiers
  const props = mods.map(m => modifierToKwarg(m)).join(', ');
  return `${base}(${props})`;
}

/** Convert a modifier node to a Python keyword argument. */
function modifierToKwarg(mod: USELNode): string {
  const name = mod.symbol.name.toUpperCase();
  const cat = mod.symbol.category;

  if (cat === 'evaluator') {
    switch (name) {
      case 'GOOD': return "quality='good'";
      case 'BAD':  return "quality='bad'";
      default:     return `${toSnakeCase(mod.symbol.name)}=True`;
    }
  }

  if (cat === 'descriptor') {
    switch (name) {
      case 'BIG':   return "size='big'";
      case 'SMALL': return "size='small'";
      case 'LONG':  return "length='long'";
      case 'SHORT': return "length='short'";
      default:      return `${toSnakeCase(mod.symbol.name)}=True`;
    }
  }

  if (cat === 'intensifier') {
    switch (name) {
      case 'VERY': return "intensity='very'";
      case 'MORE': return "intensity='more'";
      case 'NOT':  return 'negated=True';
      default:     return `${toSnakeCase(mod.symbol.name)}=True`;
    }
  }

  return `${toSnakeCase(mod.symbol.name)}=True`;
}

function compileChildNode(node: USELNode): string {
  const role = classifyNode(node);
  if (role === 'compute') return compileComputeNode(node);

  const fnName = toSnakeCase(node.symbol.name);
  if (node.children.length === 0) return `${fnName}()`;
  const args = node.children.map(c => compileChildNode(c)).join(', ');
  return `${fnName}(${args})`;
}

// ---------------------------------------------------------------------------
// Compute expression compilation
// ---------------------------------------------------------------------------

function compileComputeExpression(a: AnalysedStatement): string {
  return a.computes.map(c => compileComputeNode(c)).join('\n');
}

function compileComputeNode(node: USELNode): string {
  const name = node.symbol.name.toUpperCase();
  const cat = node.symbol.category;

  const args = node.children.map(c => {
    const num = Number(c.symbol.name);
    if (!isNaN(num)) return String(num);
    return compileChildNode(c);
  });

  if (cat === 'math') {
    const fnName = name.replace(/^COMPUTE_/, '').toLowerCase();
    return `${fnName}(${args.join(', ')})`;
  }

  if (cat === 'control') {
    if (name === 'LOOP' || name === 'COMPUTE_LOOP') {
      const count = args[0] ?? 'n';
      const body  = args[1] ?? 'pass';
      return `for i in range(${count}):\n    ${body}`;
    }
    return `${toSnakeCase(name)}(${args.join(', ')})`;
  }

  if (cat === 'compare') {
    const op = name.replace(/^COMPUTE_/, '').toLowerCase();
    if (args.length >= 2) {
      const opMap: Record<string, string> = {
        equal: '==', notequal: '!=',
        greater: '>', less: '<',
        greaterequal: '>=', lessequal: '<=',
      };
      return `(${args[0]} ${opMap[op] ?? '=='} ${args[1]})`;
    }
    return `${op}(${args.join(', ')})`;
  }

  if (cat === 'io') {
    const fnName = name.replace(/^COMPUTE_/, '').toLowerCase();
    return `${fnName}(${args.join(', ')})`;
  }

  return `${toSnakeCase(name)}(${args.join(', ')})`;
}

// ---------------------------------------------------------------------------
// Sequence compiler (for inline conditional fragments)
// ---------------------------------------------------------------------------

function compileNodeSequence(nodes: USELNode[]): string {
  const modifiers  = nodes.filter(n => classifyNode(n) === 'modifier');
  const subjects   = nodes.filter(n => classifyNode(n) === 'subject');
  const predicates = nodes.filter(n => classifyNode(n) === 'predicate');

  if (modifiers.length > 0 && (subjects.length > 0 || predicates.length > 0)) {
    const evalMod = modifiers.find(m => m.symbol.category === 'evaluator');
    const subj = subjects[0];
    if (evalMod && subj) {
      const checker = `is_${evalMod.symbol.name.toLowerCase()}`;
      const subjStr = compileSubjectNode(subj);
      if (predicates.length > 0) {
        const pred = toSnakeCase(predicates[0].symbol.name);
        return `${checker}(${pred}(${subjStr}))`;
      }
      return `${checker}(${subjStr})`;
    }
  }

  const fakeStmt: USELStatement = { type: 'statement', nodes };
  const analysis = analyseStatement(fakeStmt);
  return buildExpression(analysis);
}
